[package]
name = "lighting-store-surreal"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
lighting-core = { path = "../lighting-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
surrealdb.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
dotenvy.workspace = true
uuid.workspace = true
